# Generated by Django 3.0.4 on 2020-03-19 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
